application: whattoweartest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.gif
  static_files: favicon.gif
  upload: favicon\.gif

- url: /static
  static_dir: static

- url: /
  script: main.app
- url: /Login
  script: main.app
- url: /.*
  script: main.app
  login: required

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest